In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline
import math
from word2number import w2n
from num2words import num2words

In [ ]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
def convert_words_to_numbers(word):
    try:
        number = w2n.word_to_num(word)
        return number
    except ValueError:
        return word

In [ ]:
df['experience'] = df['experience'].apply(convert_words_to_numbers)
# m = converted_experience.median()
# mean_word = num2words(m)
df['experience'] = df.experience.fillna(math.floor(df['experience'].mean()))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
m = math.floor(df["test_score(out of 10)"].mean())
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(m)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
model = linear_model.LinearRegression()
X = df.drop('salary($)',axis='columns')
model.fit(X,df['salary($)'])

LinearRegression()

In [ ]:
model.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46799.52198459])

In [ ]:
model.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88536.36625871])

In [ ]:
model.coef_

array([2874.43853793, 1225.36778341, 2941.77277785])

In [ ]:
model.intercept_

12371.698190958909